
# Loads default set of intgrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


# 1) Add Mqtt
mqtt: !include mqtt.yaml
